In [3]:
import numpy as np
a=np.array([[45,67,68,54,2,5,7],[8,9,10,71,62,53,44]])
a[0,1:6:2]

array([67, 54,  5])

In [11]:
a[:,3]=[3,4]
print(a)

[[45 67 68  3  2  5  7]
 [ 8  9 10  4 62 53 44]]


In [15]:
b=np.array([[[45,67],[68,54]],[[8,9],[10,71]]])
print(b)

[[[45 67]
  [68 54]]

 [[ 8  9]
  [10 71]]]


######Advanced numpy indexing


In [7]:
r1=np.array([14,24,56,3,2])
r2=np.array([34,66,22,88,7])
r3=np.array([23,1,6,9,21])
r4=np.array([34,98,20,19,4])
r5=np.array([20,74,53,26,72])
arr=np.array([r1,r2,r3,r4,r5])
print(arr)

[[14 24 56  3  2]
 [34 66 22 88  7]
 [23  1  6  9 21]
 [34 98 20 19  4]
 [20 74 53 26 72]]


arr[:,2:4]

In [17]:
arr[:,-2:-4:-1]

array([[ 3, 56],
       [88, 22],
       [ 9,  6],
       [19, 20],
       [26, 53]])

In [25]:
greater_than_five=~(arr>5)
print(greater_than_five)

[[False False False  True  True]
 [False False False False False]
 [False  True False False False]
 [False False False False  True]
 [False False False False False]]


In [27]:
print(arr[greater_than_five])

[3 2 1 4]


In [29]:
#this returns a 1d array, what if we dont want 1d array but the original array size folllowing the given condn


#####where method


In [34]:
drop_under_five_arr=np.where(arr<5,arr,0)
print(drop_under_five_arr)

[[0 0 0 3 2]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [44]:
ab=np.arange(0,100,5)

ab=ab.reshape(4,5)
print(ab)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [57]:
 bc=ab[ab>50]
bc=bc.reshape(3,3)
print(bc)

[[55 60 65]
 [70 75 80]
 [85 90 95]]
